# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-02 23:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, verbose_name='código')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_level', models.CharField(choices=[('grad', 'Graduação'), ('pos', 'Pós-graduação')], max_length=255, verbose_name='nível')),
                ('code', models.CharField(max_length=7, unique=True, verbose_name='código')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('description', models.TextField(blank=True, verbose_name='ementa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='core.Institute')),
            ],
            options={
                'verbose_name': 'disciplina',
                'verbose_name_plural': 'disciplinas',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='LectureInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=2, verbose_name='turma')),
                ('year', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('lecture', models.ForeignKey(help_text='disciplina', on_delete=django.db.models.deletion.CASCADE, to='core.Lecture')),
            ],
            options={
                'verbose_name': 'turma',
                'verbose_name_plural': 'turmas',
                'ordering': ('group',),
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('academic_record', models.CharField(max_length=6, unique=True, verbose_name='RA')),
                ('course', models.CharField(blank=True, max_length=3, verbose_name='curso')),
                ('modality', models.CharField(blank=True, max_length=255, verbose_name='modalidade')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'verbose_name': 'estudante',
                'verbose_name_plural': 'estudantes',
                'ordering': ('academic_record',),
            },
        ),
        migrations.AddField(
            model_name='lectureinstance',
            name='students',
            field=models.ManyToManyField(blank=True, help_text='alunos matriculados', related_name='enrolled_in', to='core.Student'),
        ),
    ]
