# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-01 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('academic_record', models.CharField(max_length=6, unique=True, verbose_name='RA')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'verbose_name_plural': 'estudantes',
                'verbose_name': 'estudante',
                'ordering': ('academic_record',),
            },
        ),
    ]
