# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-02 00:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=7, unique=True, verbose_name='codigo')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('description', models.TextField(blank=True, verbose_name='ementa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'verbose_name_plural': 'disciplinas',
                'ordering': ('code',),
                'verbose_name': 'disciplina',
            },
        ),
        migrations.CreateModel(
            name='LectureInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=2, verbose_name='turma')),
                ('lecture', models.ForeignKey(help_text='disciplina', on_delete=django.db.models.deletion.CASCADE, to='core.Lecture')),
                ('students', models.ManyToManyField(help_text='alunos matriculados', to='core.Student')),
            ],
            options={
                'verbose_name_plural': 'turmas',
                'ordering': ('group',),
                'verbose_name': 'turma',
            },
        ),
    ]
