# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-04 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectureinstance',
            name='semester',
            field=models.IntegerField(verbose_name='semestre'),
        ),
        migrations.AlterField(
            model_name='lectureinstance',
            name='year',
            field=models.IntegerField(verbose_name='ano'),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(blank=True, max_length=255, verbose_name='curso'),
        ),
    ]
