# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-02 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_lecture_lectureinstance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='code',
            field=models.CharField(max_length=7, unique=True, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='lectureinstance',
            name='students',
            field=models.ManyToManyField(blank=True, help_text='alunos matriculados', to='core.Student'),
        ),
    ]
