# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-02 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160301_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='student',
            name='modality',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
