# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-02 03:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20160301_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectureinstance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 2, 3, 29, 5, 161861, tzinfo=utc), verbose_name='criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lectureinstance',
            name='semester',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lectureinstance',
            name='year',
            field=models.IntegerField(default=2016),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lectureinstance',
            name='students',
            field=models.ManyToManyField(blank=True, help_text='alunos matriculados', related_name='enrolled_in', to='core.Student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(blank=True, max_length=3, verbose_name='curso'),
        ),
        migrations.AlterField(
            model_name='student',
            name='modality',
            field=models.CharField(blank=True, max_length=255, verbose_name='modalidade'),
        ),
    ]
