# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-02 23:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20160302_0029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, verbose_name='código')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
            ],
        ),
        migrations.AddField(
            model_name='lecture',
            name='degree_level',
            field=models.CharField(choices=[('grad', 'graduação'), ('pos', 'pós-graduação')], default='grad', max_length=255, verbose_name='nível'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecture',
            name='institute',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.Institute'),
            preserve_default=False,
        ),
    ]
